=== XedaHQ/xeda/src/xeda/data/schemas/dry-run.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "properties": {
    "dependencies": {
      "items": {
        "additionalProperties": {
          "type": [
            "string",
            "null"
          ]
        },
        "type": "object"
      },
      "type": "array"
    },
    "nodes": {
      "items": {
        "properties": {
          "action": {
            "type": "boolean"
          },
          "deliveries": {
            "items": {
              "properties": {
                "destination": {
                  "type": "string"
                },
                "key": {
                  "type": "string"
                },
                "replaces": {
                  "type": "boolean"
                }
              },
              "required": [
                "destination",
                "key",
                "replaces"
              ],
              "type": "object"
            },
            "type": "array"
          },
          "flow": {
            "type": "string"
          },
          "identity": {
            "type": "string"
          },
          "input_types": {
            "additionalProperties": {
              "items": {
                "type": "string"
              },
              "type": "array"
            },
            "type": "object"
          },
          "inputs": {
            "items": {
              "properties": {
                "name": {
                  "type": "string"
                },
                "origin": {
                  "enum": [
                    "source",
                    "producer",
                    "none"
                  ],
                  "type": "string"
                },
                "output": {
                  "type": [
                    "string",
                    "null"
                  ]
                },
                "producer": {
                  "type": [
                    "string",
                    "null"
                  ]
                },
                "reason": {
                  "type": "string"
                },
                "sources": {
                  "items": {
                    "type": "string"
                  },
                  "type": "array"
                }
              },
              "required": [
                "name",
                "origin",
                "output",
                "producer",
                "reason",
                "sources"
              ],
              "type": "object"
            },
            "type": "array"
          },
          "name": {
            "type": "string"
          },
          "output_types": {
            "additionalProperties": {
              "items": {
                "type": "string"
              },
              "type": "array"
            },
            "type": "object"
          },
          "outputs_enabled": {
            "items": {
              "type": "string"
            },
            "type": "array"
          },
          "reason": {
            "type": "string"
          },
          "run_dir": {
            "type": "string"
          },
          "settings": {
            "type": "object"
          },
          "state": {
            "enum": [
              "fresh",
              "rejected",
              "stale",
              "unknown",
              "blocked"
            ],
            "type": "string"
          }
        },
        "required": [
          "action",
          "deliveries",
          "flow",
          "identity",
          "input_types",
          "inputs",
          "name",
          "output_types",
          "outputs_enabled",
          "reason",
          "run_dir",
          "settings",
          "state"
        ],
        "type": "object"
      },
      "type": "array"
    },
    "options": {
      "properties": {
        "clean": {
          "type": "boolean"
        },
        "outputs_to": {
          "type": [
            "string",
            "null"
          ]
        },
        "overwrite_outputs": {
          "type": "boolean"
        },
        "post_cleanup": {
          "type": "boolean"
        },
        "post_cleanup_purge": {
          "type": "boolean"
        },
        "prune_variants": {
          "type": "boolean"
        },
        "rebuild_all": {
          "type": "boolean"
        }
      },
      "required": [
        "clean",
        "outputs_to",
        "overwrite_outputs",
        "post_cleanup",
        "post_cleanup_purge",
        "prune_variants",
        "rebuild_all"
      ],
      "type": "object"
    },
    "roots": {
      "items": {
        "type": "string"
      },
      "type": "array"
    },
    "schema_version": {
      "type": "integer"
    },
    "spec": {
      "properties": {
        "design": {
          "type": [
            "string",
            "null"
          ]
        },
        "design_file": {
          "type": [
            "string",
            "null"
          ]
        },
        "flow": {
          "type": "string"
        },
        "settings": {
          "type": "object"
        },
        "target": {
          "type": [
            "string",
            "null"
          ]
        }
      },
      "required": [
        "design",
        "design_file",
        "flow",
        "settings",
        "target"
      ],
      "type": "object"
    }
  },
  "required": [
    "dependencies",
    "nodes",
    "options",
    "roots",
    "schema_version",
    "spec"
  ],
  "title": "xeda run --dry-run --json",
  "type": "object"
}

=== XedaHQ/xeda/tests/resources/documents/dry-run-1.0.json
{
  "schema_version": 1,
  "spec": {
    "flow": "vivado_synth",
    "design": "sqrt",
    "design_file": "/work/sqrt.yaml",
    "target": null,
    "settings": {
      "vivado_synth": {
        "clocks": {
          "main_clock": {
            "period": "5.5 ns"
          }
        }
      }
    }
  },
  "roots": [
    "vivado_synth"
  ],
  "options": {
    "rebuild_all": false,
    "clean": false,
    "prune_variants": false,
    "outputs_to": null,
    "overwrite_outputs": false,
    "post_cleanup": false,
    "post_cleanup_purge": false
  },
  "dependencies": [],
  "nodes": [
    {
      "name": "vivado_synth",
      "flow": "vivado_synth",
      "run_dir": "/work/xeda_run/sqrt/vivado_synth",
      "identity": "576a2a64f28d2a6468a3c3cc4fe7152dc6b86f5573475b868bd429e1511274eb",
      "state": "fresh",
      "reason": "",
      "action": false,
      "settings": {
        "verbosity": "normal",
        "nthreads": null,
        "reports_dir": "reports",
        "docker": false,
        "clocks": {
          "main_clock": {
            "name": "main_clock",
            "period": "5.5 ns",
            "rise": "0 ns",
            "duty_cycle": 0.5,
            "uncertainty": null,
            "skew": null,
            "port": null
          }
        },
        "fpga": {
          "part": "xc7a100tftg256-2L",
          "device": "xc7a100t",
          "vendor": "xilinx",
          "family": "artix-7",
          "generation": "7",
          "type": null,
          "speed": "-2L",
          "package": "ftg",
          "capacity": "100K",
          "pins": 256,
          "grade": null
        }
      },
      "inputs": [],
      "outputs_enabled": [],
      "input_types": {},
      "output_types": {
        "netlist": [
          "FpgaNetlist"
        ],
        "netlist_timing": [
          "FpgaTimingNetlist"
        ],
        "sdf": [
          "Sdf"
        ],
        "checkpoint_route": [
          "RoutedCheckpoint"
        ],
        "bitstream": [
          "Bitstream"
        ],
        "checkpoint_synth": [
          "SynthCheckpoint"
        ],
        "sdf_min": [
          "Sdf"
        ]
      },
      "deliveries": []
    }
  ]
}
