=== XedaHQ/xeda/src/xeda/data/schemas/results.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "properties": {
    "artifacts": {
      "additionalProperties": {
        "type": "string"
      },
      "type": "object"
    },
    "configuration": {
      "type": "object"
    },
    "dependencies": {
      "items": {
        "additionalProperties": {
          "type": [
            "string",
            "null"
          ]
        },
        "type": "object"
      },
      "type": "array"
    },
    "design": {
      "type": "string"
    },
    "error": {
      "properties": {
        "code": {
          "type": "string"
        },
        "exit_status": {
          "type": [
            "integer",
            "null"
          ]
        },
        "log": {
          "type": [
            "string",
            "null"
          ]
        },
        "message": {
          "type": "string"
        },
        "node": {
          "type": [
            "string",
            "null"
          ]
        }
      },
      "required": [
        "code",
        "exit_status",
        "log",
        "message",
        "node"
      ],
      "type": [
        "object",
        "null"
      ]
    },
    "finished": {
      "format": "date-time",
      "type": "string"
    },
    "flow": {
      "type": "string"
    },
    "identity": {
      "type": "string"
    },
    "inherited_variables": {
      "items": {
        "type": "string"
      },
      "type": "array"
    },
    "inputs": {
      "items": {
        "properties": {
          "name": {
            "type": "string"
          },
          "origin": {
            "enum": [
              "source",
              "producer",
              "none"
            ],
            "type": "string"
          },
          "output": {
            "type": [
              "string",
              "null"
            ]
          },
          "producer": {
            "type": [
              "string",
              "null"
            ]
          },
          "producer_run_dir": {
            "type": [
              "string",
              "null"
            ]
          },
          "producer_run_id": {
            "type": [
              "string",
              "null"
            ]
          },
          "sources": {
            "items": {
              "properties": {
                "dependency": {
                  "type": [
                    "integer",
                    "null"
                  ]
                },
                "digest": {
                  "type": "string"
                },
                "generated": {
                  "type": "boolean"
                },
                "generation": {
                  "type": [
                    "string",
                    "null"
                  ]
                },
                "path": {
                  "type": "string"
                },
                "producer": {
                  "type": [
                    "string",
                    "null"
                  ]
                }
              },
              "required": [
                "dependency",
                "digest",
                "generated",
                "generation",
                "path",
                "producer"
              ],
              "type": "object"
            },
            "type": "array"
          }
        },
        "required": [
          "name",
          "origin",
          "output",
          "producer",
          "producer_run_dir",
          "producer_run_id",
          "sources"
        ],
        "type": "object"
      },
      "type": "array"
    },
    "metric_info": {
      "additionalProperties": {
        "properties": {
          "description": {
            "type": "string"
          },
          "type": {
            "enum": [
              "number",
              "integer",
              "boolean",
              "text",
              "text_list",
              "counts",
              "numbers",
              "object"
            ],
            "type": "string"
          },
          "unit": {
            "type": [
              "string",
              "null"
            ]
          }
        },
        "required": [
          "description",
          "type",
          "unit"
        ],
        "type": "object"
      },
      "type": "object"
    },
    "metrics": {
      "type": "object"
    },
    "outcome": {
      "enum": [
        "passed",
        "rejected",
        "failed",
        "canceled"
      ],
      "type": "string"
    },
    "outputs": {
      "additionalProperties": {
        "properties": {
          "cardinality": {
            "enum": [
              "one",
              "optional",
              "many"
            ],
            "type": "string"
          },
          "design": {
            "type": [
              "object",
              "null"
            ]
          },
          "digests": {
            "items": {
              "type": "string"
            },
            "type": "array"
          },
          "kind": {
            "type": "string"
          },
          "names": {
            "items": {
              "type": "string"
            },
            "type": "array"
          }
        },
        "required": [
          "cardinality",
          "design",
          "digests",
          "kind",
          "names"
        ],
        "type": "object"
      },
      "type": "object"
    },
    "run_id": {
      "type": "string"
    },
    "runtime": {
      "type": "number"
    },
    "schema_version": {
      "type": "integer"
    },
    "settings": {
      "type": "object"
    },
    "started": {
      "format": "date-time",
      "type": "string"
    },
    "target": {
      "type": [
        "string",
        "null"
      ]
    },
    "xeda_version": {
      "type": "string"
    }
  },
  "required": [
    "artifacts",
    "configuration",
    "dependencies",
    "design",
    "error",
    "finished",
    "flow",
    "identity",
    "inherited_variables",
    "inputs",
    "metric_info",
    "metrics",
    "outcome",
    "outputs",
    "run_id",
    "runtime",
    "schema_version",
    "settings",
    "started",
    "target",
    "xeda_version"
  ],
  "title": "results.json",
  "type": "object"
}

=== XedaHQ/xeda/tests/resources/documents/results-2.0.json
{
  "schema_version": 2,
  "run_id": "4150a29a30fa438f807bf42600dc7cae",
  "xeda_version": "0.4.4.dev432+g4f28a84d2",
  "flow": "t_copy",
  "design": "d",
  "target": null,
  "identity": "8daaa75b704973bb13017a88a4c15181f9fa91d2018a5c5a7738e746d512036e",
  "configuration": {
    "rtl": {
      "top": "t",
      "parameters": {},
      "defines": {},
      "clocks": [],
      "attributes": {}
    },
    "language": {
      "vhdl": {
        "standard": null,
        "synopsys": false
      },
      "verilog": {
        "standard": null
      }
    }
  },
  "outcome": "passed",
  "error": null,
  "metrics": {
    "size": 6
  },
  "metric_info": {
    "size": {
      "description": "The size of the data.",
      "type": "integer",
      "unit": null
    }
  },
  "outputs": {
    "copy": {
      "kind": "Data",
      "cardinality": "one",
      "names": [
        "copy.txt"
      ],
      "digests": [
        "131d86ae8a44aa83e438438252fd19e0"
      ],
      "design": null
    }
  },
  "artifacts": {},
  "settings": {
    "verbosity": "normal",
    "nthreads": null,
    "reports_dir": "reports",
    "checkpoints_dir": "checkpoints",
    "outputs_dir": "outputs",
    "lib_paths": [],
    "env": {},
    "inherit_env": true,
    "docker": false,
    "docker_image": null
  },
  "inputs": [
    {
      "name": "data",
      "origin": "source",
      "producer": null,
      "output": null,
      "producer_run_id": null,
      "producer_run_dir": null,
      "sources": [
        {
          "path": "given.dat",
          "generated": false,
          "digest": "131d86ae8a44aa83e438438252fd19e0",
          "dependency": null,
          "producer": null,
          "generation": null
        }
      ]
    }
  ],
  "started": "2026-11-01T04:42:54.244162+00:00",
  "finished": "2026-11-01T04:42:54.264730+00:00",
  "runtime": 0.01844808296300471,
  "dependencies": [],
  "inherited_variables": [
    "HOME",
    "PATH"
  ]
}
